name: Coverage Report

on: push

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install --force

      - name: Run tests with coverage
        run: npx nx test frontend-challenge --coverage
      - name: Convert lcov to markdown
        run: |
          npm install -D @dhruv-m-patel/lcov-to-markdown --force
          npx @dhruv-m-patel/lcov-to-markdown test-output/jest/coverage/lcov.info > coverage.md

      - name: Show coverage markdown in summary
        run: cat coverage.md
